spring:
  application:
    name: Address-Service
  datasource:
    url: "jdbc:mysql://localhost:3306/university_db"
    username:
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8082
  servlet:
    context-path: /address-service-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
